# Generated by Django 4.0.4 on 2022-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('developer', 'developer'), ('recruiter', 'recruiter')], default='developer', max_length=9),
        ),
    ]
