# Generated by Django 4.0.5 on 2022-06-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('modification_time', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('ﬁnished', 'ﬁnished')], default='open', max_length=11)),
                ('applied_developers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='accounts.tag')),
            ],
        ),
    ]
